# Site
repository: teodoradra/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Teodora Dragusin
title: Software Engineer
email: teodoradragusin99@gmail.com
website: www.teuz.space

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  teodoradra
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: teodora-drăgușin-bb86151a1
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/sashshshshsa.png
about_content: | # this will include new lines to allow paragraphs
  My name is Teodora and I am a Java Software Engineer and I am seeking to expand my knowledge and skills towards working in a collaborative environment to develop quality software solutions that address and solve business problems. Supportive and enthusiastic team player dedicated to efficiently resolving project issues. Ability and willingness to innovate and learn new technologies, quick learner passionate about development.

  Passionate and results-driven Software Engineer with a strong foundation in Computer Science and a track record of success in diverse work environments. Seeking to contribute my technical expertise and problem-solving skills to an innovative team.


content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Spotify
        link: https://open.spotify.com/
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: February 2022 - Present
        quote: >
          Last mile delivery!
        description: | # this will include new lines to allow paragraphs
            Collaborate within the Delivery product area to enhance Spotify's content delivery platform.

            Develop and maintain backend services, written in Java and Python, which facilitate content delivery.
            
            Implement and maintain a CDN platform, using Terraform CDK and gRPC, to ensure efficient delivery to billions of Spotify users.

            Create signed URLs for users playing content, enhancing user experience.

            Lead efforts in experimentation to identify areas for improvement and optimize content delivery, utilizing BigQuery and internal Experimentation platform. 
  
      - layout: left
          title: Avenocam
          link: https://avenocam.com/
          # link_text: boringcompany.com
          sub_title: Junior Software Engineer
          caption: June 2020 - July 2021
          description: | # this will include new lines to allow paragraphs
              Contributed to the development of a live streaming software platform.
  
              Worked with technologies including Apache Kafka, Nginx, MongoDB, MySQL, AWS, Spring Boot, Java, JavaScript, and HTML 5.
              
              Collaborated with QA teams for unit and system testing, ensuring high-quality software.
  
              Developed and modified software modules to meet business requirements.
              
              Applied best coding practices to improve project effectiveness.
              
              Developed back-end applications using Java and PHP.

            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Stockholm University
        caption: 2021 - 2023
        sub_title: Master of Computer and System Science
        description: | # this will include new lines to allow paragraphs
          Specialized in advanced computer and system science topics.

          Conducted a thesis on "Optimizing Video Content Delivery on CDNs with Caching Strategies and Edge Computing".

          
      - layout: left
        title: Babes-Bolyai University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        description: | # this will include new lines to allow paragraphs
            Developed a solid understanding of computer science fundamentals.
          
            Studied a range of subjects including Programming, Cloud Infrastructure, OOP, System Design, Artificial Intelligence, and more.
          
            Conducted a thesis on "Speech Enhancement with Recurrent Neural Network".
          
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Fencing
      - Music
      - Tenis
      - Dogs 

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
